name: Index files
description: Index all files from repo to single JSON or txt file
author: Maxim Prygunov
branding:
  icon: 'thumbs-up'
  color: 'white'
inputs:
  file-type:
    description: 'File type (txt or json)'
    required: false
    default: 'json'

runs:
  using: "composite"
  steps:
    - name: Generate File Index
      shell: bash
      run: |
          find . -type f -not -path "./.git/*" -exec echo {} \; | sed 's/^\.\///' > file_list.txt
          cat file_list.txt | jq -R . | jq -s . > file_index.json
    - name: Clean Up
      shell: bash
      run: |
          if [[ "${{ github.event.inputs.file-type }}" == "txt" ]]; then
            rm file_index.json
          elif [[ "${{ github.event.inputs.file-type }}" == "json" ]]; then
            rm file_list.txt
          fi
    - name: Commit file
      uses: stefanzweifel/git-auto-commit-action@v4
